name: 5 Minute Commit

on:
  schedule:
    - cron: '5 3 5 4 *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file with current timestamp
        run: |
          echo "Last updated on $(date)" > update.txt

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Automated update at $(date)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
